# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171024_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterback',
            name='name',
        ),
        migrations.AddField(
            model_name='quarterback',
            name='firstname',
            field=models.CharField(default='ay', max_length=200),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='lastname',
            field=models.CharField(default='ay', max_length=200),
        ),
    ]
